# Generated by Django 4.0 on 2023-05-27 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='First_name',
            new_name='first_name',
        ),
    ]
